services:
  db:
    image: postgres:latest
    container_name: bot-postgres
    restart: always
    user: ${POSTGRES_USER}
    env_file:
      - .env
    expose:
      - ${POSTGRES_PORT}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      # to persist data
      - ./storage/persist:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./storage/schema/bot.sql:/docker-entrypoint-initdb.d/create_tables.sql
  bot:
    container_name: bot-server
    restart: always
    build:
      context: "."
    links:
      - db
    depends_on:
      - db
    env_file:
      - .env
    expose:
      - "8443"
    ports:
      - "8443:8443"
    command: python bot/main.py